### PR TITLE
Correct spelling mistake

### PR DESCRIPTION
**Pull request by jppunnett**

### CODE REVIEW

**Comment by xiam** [comment]
Thank you, James!

**Comment by jppunnett** [comment]
You're welcome, Xiam.
I have a couple other changes I wanted to check-in, another minor spelling correction, the other a relatively minor change: removing a variable. Do you have any rules such as needing test cases to accompany code changes? Or should I just create a pull request and let you decide at that point?

**Comment by xiam** [comment]
James,

I'm able to merge changes providing they're justified, if the modification is small enough to be justified just with a comment please do it. Test cases are expected for introducing new features or for fixing a complicated condition.

**Comment by jppunnett** [comment]
Understood.
On the https://hyperfox.org/download page, under "How to build Hyperfox on Linux/FreeBSD", I think it should be `cd $GOPATH/src/github.com/xiam`, no?

**Comment by xiam** [comment]
@jppunnett Right! the import path's parent directory was in fact wrong.

Thank you again.

**Pull request merged**
